-- MySQL Script generated by MySQL Workbench
-- Thu Dec 10 23:29:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Laboratorios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Laboratorios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Laboratorios` DEFAULT CHARACTER SET utf8 ;
USE `Laboratorios` ;

-- -----------------------------------------------------
-- Table `Laboratorios`.`Hora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorios`.`Hora` (
  `idHora` INT NOT NULL AUTO_INCREMENT,
  `inicio` TIME NOT NULL,
  `cierre` TIME NOT NULL,
  `Dia` VARCHAR(45) NOT NULL COMMENT '1=Lunes\n2=martes\n3=miercole\n4=jueves\n5=viernes \n6=sabado',
  PRIMARY KEY (`idHora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorios`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorios`.`carrera` (
  `idcarrera` INT(11) NOT NULL AUTO_INCREMENT,
  `clave` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcarrera`),
  UNIQUE INDEX `clave_UNIQUE` (`clave` ) ,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ) )
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Laboratorios`.`hora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorios`.`hora` (
  `idHora` INT(11) NOT NULL AUTO_INCREMENT,
  `inicio` TIME NOT NULL,
  `cierre` TIME NOT NULL,
  `Dia` VARCHAR(45) NOT NULL COMMENT '1=Lunes\\n2=martes\\n3=miercole\\n4=jueves\\n5=viernes \\n6=sabado',
  PRIMARY KEY (`idHora`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Laboratorios`.`laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorios`.`laboratorio` (
  `idlaboratorio` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `codigo` INT(11) NOT NULL COMMENT '121321a13',
  `edificio` VARCHAR(45) NOT NULL,
  `numero_aula` INT(11) NOT NULL,
  `foto` BLOB NULL DEFAULT NULL,
  `carrera_idcarrera` INT(11) NOT NULL,
  `Hora_idHora` INT(11) NOT NULL,
  PRIMARY KEY (`idlaboratorio`, `Hora_idHora`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ) ,
  INDEX `fk_laboratorio_carrera1_idx` (`carrera_idcarrera` ) ,
  INDEX `fk_laboratorio_Hora1_idx` (`Hora_idHora` ) ,
  CONSTRAINT `fk_laboratorio_Hora1`
    FOREIGN KEY (`Hora_idHora`)
    REFERENCES `Laboratorios`.`hora` (`idHora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_laboratorio_carrera1`
    FOREIGN KEY (`carrera_idcarrera`)
    REFERENCES `Laboratorios`.`carrera` (`idcarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Laboratorios`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorios`.`rol` (
  `idrol` INT(11) NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Laboratorios`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorios`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(45) NOT NULL COMMENT 'se agrega los nombres.\\n\\nnombre: Geovani Alberto\\n',
  `apellidos` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `foto` BLOB NULL DEFAULT NULL,
  `carrera_idcarrera` INT(11) NOT NULL,
  `rol_idrol` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `username_UNIQUE` (`username` ) ,
  UNIQUE INDEX `apellidos_UNIQUE` (`apellidos` ) ,
  UNIQUE INDEX `Nombres_UNIQUE` (`Nombres` ) ,
  INDEX `fk_usuario_carrera1_idx` (`carrera_idcarrera` ) ,
  INDEX `fk_usuario_rol1_idx` (`rol_idrol` ) ,
  CONSTRAINT `fk_usuario_carrera1`
    FOREIGN KEY (`carrera_idcarrera`)
    REFERENCES `Laboratorios`.`carrera` (`idcarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `Laboratorios`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Laboratorios`.`UsoHora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorios`.`UsoHora` (
  `idUsoHora` INT NOT NULL AUTO_INCREMENT,
  `tiempo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsoHora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorios`.`reservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorios`.`reservacion` (
  `idreservacio` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  `carrera_idcarrera` INT(11) NOT NULL AUTO_INCREMENT,
  `UsoHora_idUsoHora` INT NOT NULL,
  PRIMARY KEY (`idreservacio`, `usuario_idusuario`),
  INDEX `fk_reservacion_usuario1_idx` (`usuario_idusuario` ) ,
  INDEX `fk_reservacion_carrera1_idx` (`carrera_idcarrera` ) ,
  INDEX `fk_reservacion_UsoHora1_idx` (`UsoHora_idUsoHora` ) ,
  CONSTRAINT `fk_reservacion_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `Laboratorios`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservacion_carrera1`
    FOREIGN KEY (`carrera_idcarrera`)
    REFERENCES `Laboratorios`.`carrera` (`idcarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservacion_UsoHora1`
    FOREIGN KEY (`UsoHora_idUsoHora`)
    REFERENCES `Laboratorios`.`UsoHora` (`idUsoHora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Laboratorios`.`Notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorios`.`Notificacion` (
  `idNotificacion` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `reservacion_idreservacio` INT(11) NOT NULL,
  `reservacion_usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idNotificacion`, `reservacion_idreservacio`, `reservacion_usuario_idusuario`),
  INDEX `fk_Notificacion_reservacion1_idx` (`reservacion_idreservacio` , `reservacion_usuario_idusuario` ) ,
  CONSTRAINT `fk_Notificacion_reservacion1`
    FOREIGN KEY (`reservacion_idreservacio` , `reservacion_usuario_idusuario`)
    REFERENCES `Laboratorios`.`reservacion` (`idreservacio` , `usuario_idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
